### ISSUE TITLE
IE: Controls of HTML5 videos not working when carouselObj.$el.swipe is attached to it or its parent element

### ISSUE THREAD

**Issue by himaanshu24** [mattbryson/TouchSwipe-Jquery-Plugin#325] opened 2017-07-21 07:09 UTC
When HTML5 videos is put inside carousel with `carouselObj.$el.swipe({})` event attached to it parent item, then controls of player is not working in Internet Explorer, but the same thing works in Chrome and Firefox effortlessly.

To get it work in IE I have to use `excludedElements` to exclude the video altogether.

If it can be fixed to work like Chrome and Firefox than it is great. Otherwise, we can use above-mentioned property.

Thanks

**Comment by himaanshu24** [comment] 2017-07-21 07:21
To above problem, I found out that we can also use `preventDefaultEvents` parameter while initializing it. It works fine but creates another problem; when there is image and we use mouse pointer for swipe then the swipe does not work since image dragging is triggered.

**Comment by mattbryson** [comment] 2018-09-17 11:41
duplicate of #230

**Closed by mattbryson** 2018-09-17 11:41 UTC
