### ISSUE TITLE
touch up and down on iPhone6+ recognized as left and right (ios?)

### ISSUE THREAD

**Issue by bunower** [mattbryson/TouchSwipe-Jquery-Plugin#283] opened 2016-04-14 08:25 UTC
Hello,
i have a small problem with probably IOS Devices.
I used this script on https://www.comnet.de
On my Android Device with Chrome LG G2 work everything very well.
But on Iphone 6+ scrolling up and down are registered as left and right swipe if there is a lsmall angle in the direction of swiping up/down.
How can i fix this Problem.
You can view Output in the console.

``` javascript
$(".swiper").swipe({
           allowPageScroll:"auto",
           threshold:100,
           swipe:function(event, direction, distance, duration, fingerCount) {
                console.log("Distance: "+distance);
                console.log("duration: "+duration);
                console.log("direction: "+direction);
                console.log("fingerCount: "+fingerCount);

                if(direction=="right"){
                    $('.main_page header .left').click();
                }
                if(direction=="left"){
                    $('.main_page header .right').click();
                }
            }
});
```

**Comment by mattbryson** [comment] 2018-09-17 11:48
I cant reproduce this - less of an issue now anyway as ios has moved on so far since then.

Closing as over a year old.  Please feel free to re open if you are still having issues.

**Closed by mattbryson** 2018-09-17 11:48 UTC
Labels: Bug, IOS, direction
